# Put here properties that will be used for local debugging and local test runs.
# The properties defined in this file override any properties set in dedicated folders
batch-1.resource-location=story/training
batch-1.resource-include-patterns=*.story
# engine.composite-paths=steps/*.steps
bdd.story.location=src/main/resources/story/training/Users/zhassulan_bralin/VIVIDUS/vividus-training/src/main/resources/story/training
